#!/usr/bin/env python3
"""Regenerate data/functions/{postgres,sqlite,oracle}.txt: the built-in function
names of the latest release of each engine.

  postgres  pg_proc.dat + system_functions.sql from the REL_<N>_STABLE branch
            (every callable function/aggregate/window function, no procedures),
            plus SQL-standard special forms that are not in pg_proc.
  sqlite    PRAGMA function_list of the official amalgamation, built with the
            same options as the official CLI (math functions, FTS, RTREE, ...).
  oracle    the function pages of the Oracle SQL Language Reference, plus the
            conditions and byte/char variants that the pages only mention in
            passing.

Usage: tools/gen_function_catalogs.py --pg 18 --sqlite 2026/sqlite-amalgamation-3530400 \
           --oracle 26 [--cache DIR]
Needs network, gcc and unzip.
"""
import argparse, datetime, os, re, subprocess, sys, urllib.request

ap = argparse.ArgumentParser()
ap.add_argument("--pg", default="18")
ap.add_argument("--sqlite", default="2026/sqlite-amalgamation-3530400")
ap.add_argument("--oracle", default="26")
ap.add_argument("--cache", default="/tmp/sql-sage-catalogs")
ap.add_argument("--out", default=os.path.join(os.path.dirname(__file__), "..", "data", "functions"))
args = ap.parse_args()
os.makedirs(args.cache, exist_ok=True)
os.makedirs(args.out, exist_ok=True)
today = datetime.date.today().isoformat()


def fetch(url, name):
    path = os.path.join(args.cache, name)
    if not os.path.exists(path):
        print("fetch", url, file=sys.stderr)
        with urllib.request.urlopen(url, timeout=120) as r, open(path, "wb") as f:
            f.write(r.read())
    return path


def write(name, header, names):
    names = sorted({n.lower() for n in names})
    with open(os.path.join(args.out, name), "w") as f:
        f.write(f"# {header}\n# generated by tools/gen_function_catalogs.py on {today}; one lower-case name per line\n")
        f.write("\n".join(names) + "\n")
    print(f"{name}: {len(names)} names")


# ------------------------------------------------------------------ postgres
base = f"https://raw.githubusercontent.com/postgres/postgres/REL_{args.pg}_STABLE/src"
dat = open(fetch(f"{base}/include/catalog/pg_proc.dat", f"pg{args.pg}_proc.dat"), encoding="utf8").read()
pg = set()
for chunk in dat.split("\n{ oid")[1:]:
    m = re.search(r"proname\s*=>\s*'([^']+)'", chunk)
    kind = re.search(r"prokind\s*=>\s*'(\w)'", chunk)
    if m and (kind.group(1) if kind else "f") != "p":
        pg.add(m.group(1))
sql = open(fetch(f"{base}/backend/catalog/system_functions.sql", f"pg{args.pg}_system_functions.sql"), encoding="utf8").read()
pg |= set(re.findall(r"CREATE\s+(?:OR\s+REPLACE\s+)?FUNCTION\s+(?:\w+\.)?(\w+)", sql))
# SQL-standard special forms handled by the grammar, not stored in pg_proc
pg |= {"coalesce", "nullif", "greatest", "least", "extract", "xmlconcat", "xmlelement", "xmlexists",
       "xmlforest", "xmlparse", "xmlpi", "xmlroot", "xmlserialize"}
write("postgres.txt", f"PostgreSQL {args.pg}: pg_proc functions, aggregates and window functions (core only, no extensions)", pg)

# -------------------------------------------------------------------- sqlite
zpath = fetch(f"https://sqlite.org/{args.sqlite}.zip", "sqlite.zip")
src = os.path.join(args.cache, os.path.basename(args.sqlite))
if not os.path.exists(os.path.join(src, "sqlite3")):
    subprocess.check_call(["unzip", "-q", "-o", zpath, "-d", args.cache])
    subprocess.check_call(
        ["gcc", "-O1", "-w", "-DSQLITE_ENABLE_MATH_FUNCTIONS", "-DSQLITE_ENABLE_FTS3", "-DSQLITE_ENABLE_FTS4",
         "-DSQLITE_ENABLE_FTS5", "-DSQLITE_ENABLE_RTREE", "-DSQLITE_ENABLE_GEOPOLY", "-DSQLITE_ENABLE_DBSTAT_VTAB",
         "shell.c", "sqlite3.c", "-lpthread", "-ldl", "-lm", "-o", "sqlite3"], cwd=src)
q = "select sqlite_version(); select distinct name from pragma_function_list where builtin=1 order by name;"
out = subprocess.check_output([os.path.join(src, "sqlite3"), ":memory:", q], text=True).split("\n")
version, names = out[0], [n for n in out[1:] if re.fullmatch(r"[A-Za-z_][A-Za-z0-9_]*", n)]
write("sqlite.txt", f"SQLite {version}: PRAGMA function_list (official CLI build options)", names)

# -------------------------------------------------------------------- oracle
ob = f"https://docs.oracle.com/en/database/oracle/oracle-database/{args.oracle}/sqlrf"
ora = set()
for page in ["Single-Row-Functions", "Aggregate-Functions", "Analytic-Functions", "Object-Reference-Functions",
             "Model-Functions", "OLAP-Functions", "Data-Cartridge-Functions"]:
    html = open(fetch(f"{ob}/{page}.html", f"ora{args.oracle}_{page}.html"), encoding="utf8", errors="ignore").read()
    for href, text in re.findall(r'<a\s[^>]*href="([^"]*)"[^>]*>(.*?)</a>', html, re.S):
        if not re.match(r"^[A-Za-z0-9_\-]+\.html#GUID-", href):
            continue
        text = re.sub(r"\s+", " ", re.sub(r"<[^>]+>", "", text)).strip()
        m = re.match(r"^([A-Z][A-Z0-9_$#]*)\b", text)
        if m:
            ora.add(m.group(1))
# headings / truncated names picked up by the scrape
ora -= {"CALENDAR", "FISCAL", "RETAIL", "CORR_", "CREATE", "HAVING", "JSON", "SELECT", "SET", "REGR_", "STATS_T_TEST_"}
# documented under a shared page or as conditions, not on a page of their own
ora |= {"CORR_S", "CORR_K", "REGR_SLOPE", "REGR_INTERCEPT", "REGR_COUNT", "REGR_R2", "REGR_AVGX", "REGR_AVGY",
        "REGR_SXX", "REGR_SYY", "REGR_SXY", "STATS_T_TEST_ONE", "STATS_T_TEST_PAIRED", "STATS_T_TEST_INDEP",
        "STATS_T_TEST_INDEPU", "LENGTHB", "LENGTHC", "LENGTH2", "LENGTH4", "SUBSTRB", "SUBSTRC", "SUBSTR2",
        "SUBSTR4", "INSTRB", "INSTRC", "INSTR2", "INSTR4", "REGEXP_LIKE", "JSON_EXISTS", "JSON_EQUAL",
        "TO_UTC_TIMESTAMP_TZ"}
write("oracle.txt", f"Oracle AI Database {args.oracle}: SQL Language Reference function pages", ora)
